### ISSUE TITLE
AttributeError on macOS

### ISSUE THREAD

**Issue by kvklink** [daniperez/vale-python-package#2]
When running on a MacBook with `arm` architecture, it attempts to download the vale executable. 
However, determining the architecture appears to fail.

**Issued command (by `tox`):**
`vale --config=docs/vale/.vale.ini sync`

**Expected outcome:**
```
 SUCCESS  Downloaded package 'proselint'                                                      
 SUCCESS  Downloaded package 'Microsoft'                                                      
Downloading packages [2/2] █████████████████████████████████████████████████████████ 100% | 1s
```

**Actual outcome:**
```
py: commands[1]> vale --config=docs/vale/.vale.ini sync
* vale not found. Downloading it...
Traceback (most recent call last):
  File "/.../.tox/py/bin/vale", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/.../.tox/py/lib/python3.11/site-packages/vale/main.py", line 131, in main
    vale_bin_path = download_vale_if_missing()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.tox/py/lib/python3.11/site-packages/vale/main.py", line 102, in download_vale_if_missing
    operating_system, architecture, extension = get_target()
                                                ^^^^^^^^^^^^
  File "/.../.tox/py/lib/python3.11/site-packages/vale/main.py", line 50, in get_target
    elif os.uname().architecture.startswith("arm"):
         ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'posix.uname_result' object has no attribute 'architecture'
```

On my machine, the `os.uname()` has the following attributes:
`posix.uname_result(sysname='Darwin', nodename='hostname.local', release='22.4.0', version='Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020', machine='arm64')`

I suppose an extra if-statement in [main.py](../blob/main/vale/main.py#L48) would fix things, where it first checks for `os.uname().machine` and whether _that_ starts with `arm` instead of `os.uname().architecture`.

**Comment by daniperez** [comment]
`v2.24.4` released.  I hope it fixes your problem @kvklink .
