### ISSUE TITLE
Windows can't run vale binary without .exe extension

### ISSUE THREAD

**Issue by benallan** [daniperez/vale-python-package#8]
It seems that windows really doesn't agree with trying to run the vale_bin file, I think because it lacks a .exe extension:
```
Traceback (most recent call last):
  File "C:\Users\allan\Miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\allan\Miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\allan\Miniconda3\Scripts\vale.exe\__main__.py", line 7, in <module>
  File "C:\Users\allan\Miniconda3\lib\site-packages\vale\main.py", line 148, in main
    os.execvp(f"{vale_bin_path}", ["vale"] + sys.argv[1:])
  File "C:\Users\allan\Miniconda3\lib\os.py", line 574, in execvp
    _execvpe(file, args)
  File "C:\Users\allan\Miniconda3\lib\os.py", line 597, in _execvpe
    exec_func(file, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
```

Renaming the file with a .exe "fixes" the problem, but it's possible there is a better way.

I opened a PR to fix this, but unfortunately it involves including a new "vale.exe" placeholder next to the current vale_bin one (to ensure it's removed when uninstalling), so I can understand if the maintainers wouldn't like this!

**Comment by daniperez** [comment]
Thanks @benallan for reporting this one. I'm investigating the issue. I'll use #9 if I don't find something simpler not involving two dummy binaries.

Did you try adding the executable extension to the name of the binary (first argument in the `args` argument of `execvp`)?

```diff
# main.py
-    os.execvp(f"{vale_bin_path}", ["vale"] + sys.argv[1:])
+    os.execvp(f"{vale_bin_path}", ["vale.exe"] + sys.argv[1:])
```

My intuition says that it _won't_ work, but who knows!

I also observe that `execvp` on windows doesn't behave in the same way than in Unix (it doesn't replace the current process). I might need to fix that.

**Comment by daniperez** [comment]
Something worth trying is also:

```diff
-    os.execvp(f"{vale_bin_path}", ["vale"] + sys.argv[1:])
+    import subprocess
+    subprocess.Popen([f"{vale_bin_path}"] + sys.argv[1:])
```

**Comment by benallan** [comment]
Thanks a lot for taking a look at this! I appreciate how it can a hassle to test things on windows. 

Unfortunately, execvp still didn't work even when patching in "vale.exe" as the name: 
```
C:\Users\ben\miniconda3\lib\site-packages\vale\main.py", line 148, in main
    os.execvp(f"{vale_bin_path}", ["vale.exe"] + sys.argv[1:])
  File "C:\Users\ben\miniconda3\lib\os.py", line 574, in execvp
    _execvpe(file, args)
  File "C:\Users\ben\miniconda3\lib\os.py", line 597, in _execvpe
    exec_func(file, *argrest)
```

So I should have mentioned this in the description, but I also tried just running the vale_bin file from the command line and hit the same error, so that gave me the impression that it wouldn't work from python either. 

However, it looks like subprocess.Popen does work, and is definitely a lot better than adding a second dummy binary file to the repo!

```
    import subprocess
    subprocess.Popen([f"{vale_bin_path}"] + sys.argv[1:])
```

```
PS > vale .\README.md
* vale not found. Downloading it...
* <http.client.HTTPResponse object at 0x0000019E261EEC70> downloaded to C:\Users\ben\AppData\Local\Temp\tmp3fl969v3
* Copying C:\Users\ben\AppData\Local\Temp\tmpzjhx_quh\vale.exe to C:\Users\ben\miniconda3\lib\site-packages\vale\vale_bin
* vale extracted and copied to module path.
C:\Users\ben\Projects\vale-python-package
PS > E100 [.vale.ini not found] Runtime error

open : The system cannot find the file specified.
```

I'm more familliar with subprocess than execvp, and I might not be sure what the intent of the original execvp call was, but you're right that it doesn't replace the current process on windows. I'm not sure if we can really do a posix-style exec on windows, but if you just need to return the error code properly, perhaps you could just catch the return code from the Popen call and then use sys.exit() to forward it to whatever called the vale python wrapper? 
It might be worth checking if the stdout is properly passed when using Popen too.

Let me know if you'd like me to test anything else on windows.

**Comment by daniperez** [comment]
> I'm not sure if we can really do a posix-style exec on windows, but if you just need to return the error code properly, perhaps you could just catch the return code from the Popen call and then use sys.exit() to forward it to whatever called the vale python wrapper?
It might be worth checking if the stdout is properly passed when using Popen too.

Correct! 

Feel free to give a try to the `Popen` solution, otherwise I can do it. Myself, I'll be adding a CI testing pipeline for Windows/Mac to allow myself fixing this simple stuff in the future.

**Comment by benallan** [comment]
Sorry what I wrote above wasn't very clear, but Popen does work for me. I can add it to a PR if you prefer?

**Comment by benallan** [comment]
Great, I'll check the error codes tomorrow and make sure it works properly.

**Comment by daniperez** [comment]
> Great, I'll check the error codes tomorrow and make sure it works properly.

That will be invaluable for #11 :pray:

**Comment by benallan** [comment]
Seems to work fine on windows (using the code in #12). 

After the change, but when the .vale.ini file is missing:
```
PS > vale .\README.md
E100 [.vale.ini not found] Runtime error

open : The system cannot find the file specified.

Execution stopped with code 1.

PS > $LastExitCode
2
```
I'm not really sure if 2 is the proper exit code for that situation; the output mentions E100 and "stopped with code 1". But at least it's not 0.

After I create the .vale.ini file, we get exit code 0 like we wanted:
```
PS > vale .\README.md
✔ 0 errors, 0 warnings and 0 suggestions in 0 files.

PS > $LastExitCode
0
```
